name: CJSON-Main

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches: [ master ]

jobs:
  CJSON_MASTER:
    strategy:
      matrix:
        build_type: [Release, RelWithDebInfo, MinSizeRel, Debug]
        target_system: [ windows-2022 ]
    runs-on: ${{ matrix.target_system }}

    steps:
      - uses: actions/checkout@v4

      - name: Prime ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.target_system }}-${{ matrix.build_type }}
          max-size: 1000M

      - name: Get Deps (LuaJIT)
        shell: bash
        # if: steps.cache-Lua.outputs.cache-hit != 'true'
        run: CI/get_deps.sh ${{ matrix.target_system }}

      - name: Configure
        shell: bash
        run: |
          LUA_DIR=LuaJIT/ cmake .

      - name: Build
        if: runner.os == 'Windows'
        run: |
          cmake --build . --config ${{ matrix.build_type }}

        -name: Move Release Files

      - name: Upload Release
        if: github.event_name != 'pull_request'
        if: runner.os == "Windows"
        run: |
          mv ${{ github.workspace }}/${{ matrix.build_type }}/cjson.dll ${{ github.workspace }}/cjson-${{ matrix.build_type }}.dll
        if: runner.os != "Windows"
        run: |
          mv ${{ github.workspace }}/cjson.so ${{ github.workspace }}/cjson-${{ matrix.build_type }}.so
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Stable-CI
          files: ${{ github.workspace }}/cjson-${{ matrix.build_type }}${{ runner.os == 'Windows' && '.dll' || '.so' }}
          body: |
            CI Build for Dreamweave IO2 fork

      - name: Upload Artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: cjson-${{ matrix.build_type }}-${{matrix.target_system}}
          if: runner.os == "Windows"
          path: ${{ github.workspace }}/${{ matrix.build_type }}/cjson.dll
          if: runner.os != "Windows"
          path: ${{ github.workspace }}/cjson.so
