name: CJSON-Main

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  pull_request:
    branches: [ master ]

jobs:
  CJSON_MASTER:
    strategy:
      matrix:
        build_type: [Release, RelWithDebInfo, MinSizeRel, Debug]
        target_system: [ ubuntu-22.04, windows-2022 ]
    runs-on: ${{ matrix.target_system }}
    env:
      build_extension: ${{ matrix.target_system == 'windows-2022' && '.dll' || '.so' }}
      # BUILD_DIR: D:/a/Lua-io2/Lua-io2/${{ matrix.build_type}}/

    steps:
      - uses: actions/checkout@v4

      - name: Prime ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.target_system }}-${{ matrix.build_type }}
          max-size: 1000M

      - name: Configure
        shell: bash
        run: cmake .

      - name: Build
        run: |
          cmake --build . --config ${{ matrix.build_type }}
          echo ${{ env.build_extension }}
          # mv ${{ env.BUILD_DIR }}/io2.dll ${{ env.BUILD_DIR }}/io2-${{ matrix.build_type }}.dll

      - name: Upload Release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Stable-CI
          files: ${{ env.BUILD_DIR }}/cjson${{ matrix.build_type }}${{ env.build_extension }}
          body: |
            CI Build for Dreamweave IO2 fork

      - name: Upload Artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.BUILD_DIR }}/cjson${{ matrix.build_type }}${{ env.build_extension }}
          name: cjson-${{ matrix.build_type }}
